services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-db
    environment:
      - ORACLE_PASSWORD=123456
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: always

volumes:
  oracle-data:
    driver: local
